# Minicurso Python - SEMMAP 2

## Matrizes

In [29]:
vetor = [1, 2, 1]
matriz = [[1, 2, 3], 
          [4, 5, 6]]

print(vetor)
print(matriz)

[1, 2, 1]
[[1, 2, 3], [4, 5, 6]]


In [30]:
print(matriz[0][-1])
print(matriz[:][-1])

3
[4, 5, 6]


## Numpy

In [1]:
import numpy as np

### Criando Arrays

In [35]:
np_vec = np.array(vetor)
np_mat = np.array(matriz)

print(np_vec)
print(np_mat)

[1 2 1]
[[1 2 3]
 [4 5 6]]


In [44]:
z = np.zeros([3, 3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
o = np.ones([3,3])
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
print(np.arange(10, 30, 5))
print(np.arange(0, 1, 0.1))

[10 15 20 25]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [68]:
from numpy import pi
x = np.linspace(0,2,9)
print(x, "shape:", x.shape)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ] shape: (9,)


In [70]:
x = np.linspace(0,2*pi,100)
print(x[-5:], "shape:", x.shape)
f = np.sin(x)
print(f[-5:])

[6.02931923 6.09278575 6.15625227 6.21971879 6.28318531] shape: (100,)
[-2.51147987e-01 -1.89251244e-01 -1.26592454e-01 -6.34239197e-02
 -2.44929360e-16]


### Acessando Arrays

In [99]:
z = np.random.randint(low= 0, high = 10, size = [4, 4])
print(z)

[[3 8 9 2]
 [0 4 6 0]
 [5 8 2 3]
 [6 8 8 6]]


In [100]:
z[1, 1]

4

In [101]:
z[0]

array([3, 8, 9, 2])

In [102]:
z[:, 0]

array([3, 0, 5, 6])

In [103]:
z[1, 1] = 50
z

array([[ 3,  8,  9,  2],
       [ 0, 50,  6,  0],
       [ 5,  8,  2,  3],
       [ 6,  8,  8,  6]])

In [104]:
z[:, 2] = 20
z

array([[ 3,  8, 20,  2],
       [ 0, 50, 20,  0],
       [ 5,  8, 20,  3],
       [ 6,  8, 20,  6]])

In [105]:
z.shape

(4, 4)

In [106]:
z.size

16

In [107]:
type(z)

numpy.ndarray

### Manipulando dimensões 

In [147]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


#### O "reshape" retorna uma nova array do tamanho especificado

In [155]:
b = a.reshape(4, 4)
print(b)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### o "resize" muda a própia array, sem retornar nada

In [152]:
a.resize(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### "ravel" retorna a array 'esticada'

In [153]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### e ".T" retorna o transposto da array

In [156]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

#### Se uma dimensão foi dada como -1 no reshape, ela é calculada automaticamente

In [158]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [161]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

### Operações básicas
#### Operações aritméticas básicas são aplicadas a cada elemento

In [113]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [114]:
a-b

array([20, 29, 38, 47])

In [116]:
b**2

array([0, 1, 4, 9])

In [117]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [119]:
a < 35

array([ True,  True, False, False])

In [120]:
a * b

array([  0,  30,  80, 150])

#### Para fazer o puduto de matrizes precisamos usar o método np.dot ou o operador "@"

In [124]:
a = np.array([[1, 1], 
              [0, 1]])

b = np.array([[2, 0], 
              [3, 4]])

In [125]:
 a * b

array([[2, 0],
       [0, 4]])

In [126]:
a @ b

array([[5, 4],
       [3, 4]])

In [127]:
a.dot(b)

array([[5, 4],
       [3, 4]])

#### Quando operamos com arrays de tipos diferentes, o resultado possui o tipo mais "geral" ou preciso

In [128]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
print(a)
print(b)

[1 1 1]
[0.         1.57079633 3.14159265]


In [130]:
print(a.dtype.name)
print(b.dtype.name)

int32
float64


In [131]:
c = a + b
print(c)
print(c.dtype.name)

[1.         2.57079633 4.14159265]
float64


In [132]:
d = np.exp(c*1j)
print(d)
print(d.dtype.name)

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


#### Temos também muitas operações úteis comum entres todas as arrays de numpy

In [133]:
a = np.random.random((2,3))
print(a)

[[0.73903608 0.42024006 0.31358649]
 [0.68663716 0.76939177 0.13505953]]


In [134]:
a.sum()

3.0639510958822003

In [135]:
a.max()

0.7693917733093855

In [136]:
a.min()

0.13505953100975476

#### Por padrão, essas funções são aplicadas nas arrays tratando elas como uma lista de números (1D), mas podemos especificar em qual eixo elas devem ser aplicadas

In [138]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [139]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [140]:
b.max(axis=0)

array([ 8,  9, 10, 11])

In [141]:
b.min(axis=0)

array([0, 1, 2, 3])

### Unindo arrays

In [163]:
a = np.zeros([4,4])
b = np.ones([4,4])
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [164]:
np.hstack([a, b])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [165]:
np.vstack([a, b])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [166]:
a = np.zeros(4)
b = np.ones(4)
print(a)
print(b)

[0. 0. 0. 0.]
[1. 1. 1. 1.]


In [167]:
a.reshape(4, 1)

array([[0.],
       [0.],
       [0.],
       [0.]])

In [168]:
b.reshape(4, 1)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [169]:
np.hstack([a.reshape(4, 1), b.reshape(4, 1)])

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [170]:
np.column_stack([a, b])

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

## Importando/Exportando Dados

In [5]:
x = np.linspace(1, np.pi, 1000)
y = np.sin(x)

data = np.column_stack([x, y])

In [6]:
np.savetxt("data.txt", data, delimiter=",")

In [12]:
f = open("data.txt", "r")
print(f.readlines()[:10])
f.close()

['1.000000000000000000e+00,8.414709848078965049e-01\n', '1.002143736389979667e+00,8.426273161017300284e-01\n', '1.004287472779959556e+00,8.437797750141416975e-01\n', '1.006431209169939223e+00,8.449283562488864030e-01\n', '1.008574945559919112e+00,8.460730545275400027e-01\n', '1.010718681949898778e+00,8.472138645895223030e-01\n', '1.012862418339878667e+00,8.483507811921222608e-01\n', '1.015006154729858334e+00,8.494837991105214092e-01\n', '1.017149891119838223e+00,8.506129131378180608e-01\n', '1.019293627509817890e+00,8.517381180850513989e-01\n']


In [13]:
read_data = np.loadtxt("data.txt", delimiter=",")
print(read_data[:10])

[[1.         0.84147098]
 [1.00214374 0.84262732]
 [1.00428747 0.84377978]
 [1.00643121 0.84492836]
 [1.00857495 0.84607305]
 [1.01071868 0.84721386]
 [1.01286242 0.84835078]
 [1.01500615 0.8494838 ]
 [1.01714989 0.85061291]
 [1.01929363 0.85173812]]


In [14]:
np.save("data.npy", data)
read_data = np.load("data.npy")
print(read_data[:10])

[[1.         0.84147098]
 [1.00214374 0.84262732]
 [1.00428747 0.84377978]
 [1.00643121 0.84492836]
 [1.00857495 0.84607305]
 [1.01071868 0.84721386]
 [1.01286242 0.84835078]
 [1.01500615 0.8494838 ]
 [1.01714989 0.85061291]
 [1.01929363 0.85173812]]
